import { useState, useEffect } from "react";

export interface Customer {
  _id: any;
  userId?: string;
  name: string;
  lastName?: string;
  address: string;
  phone: any;
  dob?: string;
  tags?: string[] | string;
  status: string;
  schedule?: string;
  councilId?: any | null;
  createdAt?: string;
  type: string;
  email?: string;
  company?: string;
  totalOrders?: number;
  isActive?: boolean;
  area: string;
  details: string | null;
}

export const useCustomerList = () => {
  const [userData, setUserData] = useState<Customer[]>([]);
  const [metaData, setMetaData] = useState<{ total: number }>({ total: 0 });
  const [loading, setLoading] = useState<boolean>(false);

  useEffect(() => {
    setLoading(true);

    // Dummy customer data
    const defaultClients: Customer[] = [
      {
        "_id": 230691,
        "name": "Charles 'O CONNOR",
        "address": "Longmire Centre, 181 Langley Lane, Wythenshaw, Manchester, M22 4HY",
        "area": "Wythenshawe",
        "phone": "07444180807",
        "dob": "23-Apr-1998",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230644,
        "name": "Favour Abiodun",
        "address": "9 Ridsdale Avenue , Manchester, m20 1eq",
        "area": "Chorlton",
        "phone": "07908301119",
        "dob": "07-Nov-2006",
        "type": "MCC SPOT",
        "tags": "Nuts| Dust| Dairy|",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230670,
        "name": "Nasim Aktar",
        "address": "99 Davonshire Street, , Manchester, Lancashire, M13 9HY",
        "area": "Longsight",
        "phone": "Shabina (Daughter) 07827920888, Parvaiz (Son) 07723109901",
        "dob": "28-Dec-1940",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 52,
        "name": "Maqsood Ashraf",
        "address": "42 Brentbridge Road, M14 6AS, Manchester, M14 6AS",
        "area": "Chorlton",
        "phone": "Landline - 0161 445 1194, Parveen (Sister) - 07966891049",
        "dob": "21-Apr-1960",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230553,
        "name": "Mohamed  Aslam",
        "address": "31 Vaughan Road, Chorlton, Manchester, M21 0ZL",
        "area": "Chorlton",
        "phone": "0161 670 5985 - 07904737776, Wes - (Son)07870333336",
        "dob": "02-Jun-1946",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 73,
        "name": "Josephine Bailey",
        "address": "5 Bulfinch Walk, M21 7RG, Manchester, M21 7RG",
        "area": "Chorlton",
        "phone": "Christine(Daughr)- 07790754061",
        "dob": "24-Dec-1944",
        "type": "MCC SPOT",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 3,
        "name": "Roy Baker",
        "address": "8 Craigmore Avenue, M20 2ZL, Manchester, England, M20 2ZL",
        "area": "Chorlton",
        "phone": "Michelle - 07876472062, Michelle - 07876472062",
        "dob": "08-Dec-1936",
        "type": "Private",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": 4343806
      },
      {
        "_id": 230654,
        "name": "Maeve Barbara O`Connor",
        "address": "32 Finney Drive , Manchester, Lancashire, M21 9DS",
        "area": "Chorlton",
        "phone": "07975751165, 07975751165 - Husband",
        "dob": "16-Apr-1947",
        "type": "MCC SPOT",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230352,
        "name": "Karen Barret",
        "address": "14 Hollyhey Drive, Manchester, M23 0DZ, Manchester, M23 0DZ",
        "area": "Wythenshawe",
        "phone": "07487494344",
        "dob": "17-Sep-1967",
        "type": "MCC SPOT",
        "tags": "Ibuprofen",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230184,
        "name": "William John  Beckett",
        "address": "19 Glebelands Road, M23 1HG, Manchester, M23 1HG",
        "area": "Wythenshawe",
        "phone": "0161 998 0088, 07709228189",
        "dob": "05-Dec-1985",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230291,
        "name": "Lilian Dorothy Bellfield",
        "address": "20 Braintree Road, M22 0HH, Manchester, M22 0HH",
        "area": "Wythenshawe",
        "phone": "0161 283 3125, 07873815733",
        "dob": "28-Apr-1941",
        "type": "MCC SPOT",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230153,
        "name": "Amy Boss",
        "address": "498 Claremont Road, M14 5WA, Manchester, Greater Manchester, M14 5WA",
        "area": "Chorlton",
        "phone": "0161 224 5672, 07468213956",
        "dob": "21-Mar-1950",
        "type": "MCC SPOT",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 7,
        "name": "Christopher Bowcock",
        "address": "Flat 2 Slade Mount, Slade Lane, Longsight, , Manchester, Lancashire, M19 2HB",
        "area": "Chorlton",
        "phone": "Christopher 07598808578, Dawn Bowcock - 0161-718-7632",
        "dob": "31-Mar-1957",
        "type": "MCC SPOT",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": 219051
      },
      {
        "_id": 230707,
        "name": "Carol Bowers",
        "address": "11 Farrington Avenue, Manchester, Lancashire, M20 1ER",
        "area": "Didsbury",
        "phone": "0161 445 8159",
        "dob": "28-Dec-1943",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 71,
        "name": "Joseph Branche",
        "address": "254 City Road, Manchester, M15 4FA",
        "area": "Chorlton",
        "phone": "0161 877 8795, Henry 01282612137-07709120388",
        "dob": "17-Jul-1926",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230685,
        "name": "Cecil Brown",
        "address": "3 Maitland Avenue , Chorlton, M21 7ND",
        "area": "Chorlton",
        "phone": "07747114316, 07747114316",
        "dob": "07-Aug-1937",
        "type": "MCC SPOT",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230659,
        "name": "Camran Butt",
        "address": "19 Bruntwood Lane Cheadle, M21 0SH, Manchester, Cheshire, M21 0SH",
        "area": "Wythenshawe",
        "phone": "07427632049, 07427632049",
        "dob": "14-Feb-1985",
        "type": "IB Budget",
        "tags": "DNAR in place| Anti-inflammatory medication| Penicillin|",
        "status": "Active",
        "schedule": "N",
        "details": "",
        "councilId": "0001"
      },
      {
        "_id": 230706,
        "name": "Ateeq Ur Rehman Butt",
        "address": "68 Stainer Street, Manchester, Lancashhire, M12 4PB",
        "area": "Longsight",
        "phone": "07424660719, Shabana (Wife) 07404826474",
        "dob": "18-Nov-1973",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230139,
        "name": "May Cannon",
        "address": "140D Gladeside Road, M22 9GT, Manchester, Greater Manchester, M22 9GT",
        "area": "Wythenshawe",
        "phone": "07384 382778, 07518177789",
        "dob": "17-Oct-1961",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230669,
        "name": "Maevis Carter",
        "address": "7 Yew Street , Manchester, M15 5YW",
        "area": "Chorlton",
        "phone": "Jan Bell - sister -07976055024, 07976055024",
        "dob": "11-Mar-1943",
        "type": "Private",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230694,
        "name": "Daniel Castille",
        "address": "236 Cornishway, Wythenshawe , Manchester, Lancashire, M22 1SU",
        "area": "Wythenshawe",
        "phone": "07860755664",
        "dob": "04-Dec-1975",
        "type": "MCC SPOT",
        "tags": "DNAR in place| Sertraline and Penicillian|",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230315,
        "name": "Jawaid Akbar  Choudhury",
        "address": "Flat 31  8 Wilbraham Road, M14 6JW, Manchester, M14 6JW",
        "area": "Chorlton",
        "phone": "07508888411-son",
        "dob": "18-Oct-1945",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230519,
        "name": "Meher Akhtar Choudhury",
        "address": "28 Eileen Grove West, Rusholme, Manchester, M14 5NW",
        "area": "Chorlton",
        "phone": "0161 248 6613 - Daughter Rosie, 0161 818 9661",
        "dob": "14-Aug-1945",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": 26478
      },
      {
        "_id": 230370,
        "name": "Arthur  Choularton",
        "address": "56 Grosvenor Street, Manchester, Lancashire, M1 7EW",
        "area": "Longsight",
        "phone": "0161 273 5740",
        "dob": "18-Mar-1943",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230170,
        "name": "Naomi  Clarke",
        "address": "5 Le Bas House, 46 Ormskirk Avenue , Manchester, M20 1HJ",
        "area": "Didsbury",
        "phone": "0161 881 1385, 07534933520",
        "dob": "12-Aug-1970",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230688,
        "name": "Allan Cope",
        "address": "Flat 56, Gorton Mill House, 420 Abbey Hey Lane, Gorton, Manchester, M18 8DU",
        "area": "Longsight",
        "phone": "07511002260",
        "dob": "14-Jul-1961",
        "type": "Man CCG",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230668,
        "name": "George A Cuthbert",
        "address": "19 Henfield Walk, Machester, M22 9QF",
        "area": "Wythenshawe",
        "phone": "07385856375, David (Brother) 07724549424",
        "dob": "23-Oct-1957",
        "type": "MCC SPOT",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230703,
        "name": "Patricia Darragh",
        "address": "14 Penroy Avenue , Manchester, Lancashire, M20 2ZH",
        "area": "Didsbury",
        "phone": "07505269246, 0161 374 0501",
        "dob": "05-Aug-1944",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230695,
        "name": "Peta  Davenport",
        "address": "19 Cherington Close, Wythenshawe , Manchester, Lancashire, M23 0FE",
        "area": "Wythenshawe",
        "phone": "01619985653, 07900514656 (Brother-Stephen)",
        "dob": "02-Jan-1940",
        "type": "Private",
        "tags": "Anti-inflammatory medication",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230533,
        "name": "June Davis",
        "address": "Flat 34, Tangmere Court, Dudley Road, , Manchester, M16 8DF",
        "area": "Chorlton",
        "phone": "0161 861 0997, 07773668853",
        "dob": "21-Jun-1924",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230451,
        "name": "Mohammed Dawood",
        "address": "9 Brent Road, Northern Moor, M23 0UE, Manchester, M23 0UE",
        "area": "Wythenshawe",
        "phone": "0161 998 30, 0161 998 3029",
        "dob": "06-Jan-1937",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230381,
        "name": "James  Delaney",
        "address": "6 Kershaw Walk, Manchester, Lancashire, M12 4AL",
        "area": "Longsight",
        "phone": "07841932555",
        "dob": "10-May-1958",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": 230381
      },
      {
        "_id": 230372,
        "name": "Eric  Dixon",
        "address": "35 Meldon Road, , Manchester, Greater Manchester, M13 0TT",
        "area": "Longsight",
        "phone": "0161 248 5482, 07949887529 (Niece)",
        "dob": "18-May-1951",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": 230372
      },
      {
        "_id": 230682,
        "name": "Teresa  Doyle",
        "address": "3 Dunbar Avenue, Manchester, Lancashire, M23 2XR",
        "area": "Wythenshawe",
        "phone": "0161 437 6918,Son 07843051736, Marion (Daughter) 07875320678",
        "dob": "14-Sep-1926",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230288,
        "name": "Brian Kevin Eastlake",
        "address": "25 Ellenbrook Road, M22 1HJ, Wythenshawe, M22 1JH",
        "area": "Wythenshawe",
        "phone": "0161 283 9255, Kyle McDerm nephew 07926182216",
        "dob": "28-Apr-1974",
        "type": "MCC SPOT",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 68,
        "name": "Salima Eghrada",
        "address": "112 Alexandra Road South, M16 8WU, Manchester, M16 8WU",
        "area": "Chorlton",
        "phone": "Mya (granddaughter)07710798916",
        "dob": "01-Jan-1934",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230704,
        "name": "Russell Wayne Folawiyo",
        "address": "5 Bankside Court , Manchester, County, M12 5GA",
        "area": "Didsbury",
        "phone": "07955115613",
        "dob": "22-Jun-1965",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230652,
        "name": "Jodie  Greaves",
        "address": "548 Princess Road , Manchester, M21 7QA",
        "area": "Chorlton",
        "phone": "07526149749",
        "dob": "09-Dec-1971",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230556,
        "name": "Samuel Griffin",
        "address": "Flat 38 Thorngrove House, 9 Thorngrove Avenue, Manchester, M23 9PQ",
        "area": "Wythenshawe",
        "phone": "0161 962 8282, 07595021984 - Angela",
        "dob": "21-Apr-1941",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230308,
        "name": "Adrian  Grogan",
        "address": "Flat 31 Elmswood Park, 32 Bowes Street, M14 4UZ, Manchester, M14 4UZ",
        "area": "Chorlton",
        "phone": "07468213956, 01617101664",
        "dob": "31-Jan-1947",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230220,
        "name": "Margaret Guilfoyle",
        "address": "2 Beeton Grove, Manchester, Lancashire, M13 0DL",
        "area": "Longsight",
        "phone": "0161 225 6001, 07946443007 Jackie (daughter)",
        "dob": "13-Dec-1939",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230384,
        "name": "Majeed  Haroon",
        "address": "61 Stamford Torad, Manchester, Lancashire, M13 0SW",
        "area": "Longsight",
        "phone": "0161 -2573739, Father - 07470296468",
        "dob": "16-Oct-1979",
        "type": "MCC SPOT",
        "tags": "Hayfever",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": 230384
      },
      {
        "_id": 30,
        "name": "Kassim Hasham",
        "address": "14 Calverley Avenue, Manchester, Lancashire, M19 2JR",
        "area": "Chorlton",
        "phone": "0161 224 2672",
        "dob": "04-Jun-1950",
        "type": "IB Budget",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 34,
        "name": "Kalias Hassan",
        "address": "3 Valley Road , Manchester, SK8 1HY",
        "area": "Wythenshawe",
        "phone": "07899086699",
        "dob": "13-Jan-2005",
        "type": "Private,  WN",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230687,
        "name": "Vicky Hayes",
        "address": "37 Raymond Road, Northern Moor, Manchester, M23 0FD",
        "area": "Wythenshawe",
        "phone": "07973450729, 07973450729",
        "dob": "01-Jun-1956",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230410,
        "name": "Ellenor Henry",
        "address": "25 Holdgate Close, Manchester, M15 5EP, Manchester, M15 5EP",
        "area": "Chorlton",
        "phone": "0161 232 7833, Sheryl-daughter-07903930428",
        "dob": "07-Dec-1940",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230517,
        "name": "Verion Faye  Henry",
        "address": "34 Nevada Street, Manchester, United Kingdom, m13 9GQ",
        "area": "Longsight",
        "phone": "0161 273 6916, 07958 617 483",
        "dob": "10-Jul-1966",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230402,
        "name": "William  Higgins",
        "address": "6 Fulshaw Walk, Manchester, Lancashire, M13 9WD",
        "area": "Longsight",
        "phone": "07960 899573",
        "dob": "06-Aug-1931",
        "type": "MCC SPOT",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": 230402
      },
      {
        "_id": 230364,
        "name": "Daphne Hood",
        "address": "34 Bowdon Avenue, Manchester, M14 7HD, Manchester, M14 7HD",
        "area": "Chorlton",
        "phone": "0161 232 9960, 07802541542 - Nigel",
        "dob": "11-Aug-1935",
        "type": "MCC SPOT",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230283,
        "name": "Mohammed Hussain",
        "address": "6 Athol Road, Manchester, Lancashire, M16 8QN",
        "area": "Chorlton",
        "phone": "Daughter Robina - 07977487442, Son Aktar - 07723098523",
        "dob": "15-Jun-1932",
        "type": "MCC SPOT",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230689,
        "name": "Bana Begum Hussain",
        "address": "23 Rainforth Street , Manchester, M13 0RP",
        "area": "Longsight",
        "phone": "0161 248 7291",
        "dob": "10-Sep-1946",
        "type": "MCC SPOT",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230633,
        "name": "Peter  Johnson",
        "address": "155 Egerton Road South, Manchester, M21 0XD",
        "area": "Chorlton",
        "phone": "0161 881 6637, 07767212911",
        "dob": "21-Jul-1950",
        "type": "Private",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230506,
        "name": "Bintou Joof",
        "address": "10 Pewsey Road, , Manchester, Lancashire, M22 5BA",
        "area": "Wythenshawe",
        "phone": "07383811593",
        "dob": "05-Jul-1975",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 85,
        "name": "Raj Kaushal",
        "address": "517 Wilbraham Road, Manchester, M21 0UF",
        "area": "Chorlton",
        "phone": "Son-Ash-07876400783",
        "dob": "03-Dec-1937",
        "type": "Private",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230458,
        "name": "Eva Kertesz",
        "address": "9 Horstead Walk, Levenshulme, M19 3BE, Manchester, M19 3BE",
        "area": "Longsight",
        "phone": "07801985727, 07719869290",
        "dob": "11-Sep-1941",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230530,
        "name": "Parveen  Khan",
        "address": "1 St Werburgh's Road , Manchester, M21 0TW",
        "area": "Chorlton",
        "phone": "0161 881 7678, 07375062863 -Rushna",
        "dob": "10-Feb-1943",
        "type": "MCC SPOT",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": 3421303
      },
      {
        "_id": 230526,
        "name": "Brian King",
        "address": "Flat 18, 51 Manor Drive, Manchester, M21 7JU, Manchester, M21 7JU",
        "area": "Chorlton",
        "phone": "07977771582",
        "dob": "16-Jun-1971",
        "type": "MCC SPOT",
        "tags": "Hayfever",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230386,
        "name": "Nomalanga Kona",
        "address": "23 Falshaw Way, Manchester, M18 7TJ",
        "area": "Longsight",
        "phone": "07973383520, 07725752120 (Cousin)",
        "dob": "26-May-1981",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230486,
        "name": "Vera Lawrence",
        "address": "Flat 30, Adastral House, Wilbraham Road , Manchester, United Kingdom, M21 0UD",
        "area": "Chorlton",
        "phone": "0161 881 9436, Linda (Daughter) 0161 864 4847",
        "dob": "19-Feb-1927",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": 5032689
      },
      {
        "_id": 16,
        "name": "Irene Leishman",
        "address": "25 Chevington Drive Harpurhey, Manchester, M9 5GW",
        "area": "Chorlton",
        "phone": "07984900679",
        "dob": "06-Feb-1961",
        "type": "IB Budget",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230441,
        "name": "Ann Shirley Lyons",
        "address": "164 Ravenscarr Crescent, Wythenshawe, M22 0HN, Manchester, M22 0HN",
        "area": "Wythenshawe",
        "phone": "0161 448 1776, 07936408182 - Paul",
        "dob": "26-Mar-1963",
        "type": "MCC SPOT",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230159,
        "name": "Clifford Manners",
        "address": "52 Clinton Avenue, M14 7LG, Manchester, Greater Manchester, M14 7LG",
        "area": "Chorlton",
        "phone": "07448074771 (son), 07745408702",
        "dob": "15-Feb-1944",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230699,
        "name": "Khulile  Mbatha",
        "address": "5 Farrington Avenue , Manchester, Greater Manchester, M20 1ER",
        "area": "Didsbury",
        "phone": "07711805645",
        "dob": "25-Feb-1967",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230310,
        "name": "Beryl  McCartney",
        "address": "16 Nuffield Road, Wythenshawe, M22 9UG, Wythenshawe, M22 9UG",
        "area": "Wythenshawe",
        "phone": "07594494598",
        "dob": "01-Dec-1934",
        "type": "MCC SPOT",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230700,
        "name": "Maureen  McCluskey",
        "address": "2 Scarisbrick Avenue, Manchester, Greater Manchester, M20 6EU",
        "area": "Didsbury",
        "phone": "0161 445 4475, 07703801191",
        "dob": "01-Dec-1925",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230164,
        "name": "Denise McElwee",
        "address": "61 Lownorth Road, Wythenshawe, M22 0JU",
        "area": "Wythenshawe",
        "phone": "0161 437 4131",
        "dob": "02-Oct-1955",
        "type": "MCC SPOT",
        "tags": "Trimethoprim antibiotic",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 27,
        "name": "Ian McHugh",
        "address": "266 Brantingham Road, Manchester, Lancashire, M21 0QZ",
        "area": "Chorlton",
        "phone": "07968629063",
        "dob": "11-Dec-1963",
        "type": "Man CCG",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230637,
        "name": "Joanna Mcnicol",
        "address": "257, Manley Road, Manchester, M21 0RE",
        "area": "Chorlton",
        "phone": "07970286684, 07970286684",
        "dob": "15-Jan-1977",
        "type": "Private",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230681,
        "name": "Sadiqun Mohammed",
        "address": "57 St Werburghs Road, M21 0UN, Manchester, Lancashire, M21 0UN",
        "area": "Chorlton",
        "phone": "0161 2836734, Yasmin (Daughter) 07912693113",
        "dob": "15-Jun-1932",
        "type": "MCC SPOT",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230680,
        "name": "Yvonne Marie  Morgan",
        "address": "9 Barbara Castle Square, Manchester, Lancashire, M13 9HW",
        "area": "Longsight",
        "phone": "0161 272 6640, Wendy (Daughter) 07957197675",
        "dob": "23-Dec-1938",
        "type": "Private,  MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230684,
        "name": "Khan Mulik",
        "address": "278 Mauldeth Road West, Chorlton, Manchester, M21 7TG",
        "area": "Chorlton",
        "phone": "07730414829",
        "dob": "08-May-1942",
        "type": "Private",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230518,
        "name": "Thomas  Murphy",
        "address": "22 Ardwick Terrance , Manchester, M12 4DL",
        "area": "Longsight",
        "phone": "07903460632",
        "dob": "14-Apr-1951",
        "type": "MCC SPOT",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": "E05011351"
      },
      {
        "_id": 230388,
        "name": "Consie Myers",
        "address": "6 Chalcombe Grange, Manchester, Greater Manchester, M12 4HQ",
        "area": "Longsight",
        "phone": "0161 273 4270, 07713 345417",
        "dob": "05-Jun-1946",
        "type": "MCC SPOT",
        "tags": "Penicillin",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230636,
        "name": "Mohammed  Naeem",
        "address": "64 Addison Crescent , Manchester, M16 0LX",
        "area": "Longsight",
        "phone": "07479965133",
        "dob": "25-Apr-1986",
        "type": "Private",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230396,
        "name": "Sharon  Neate",
        "address": "6 Royds Close, Manchester, Greater Manchester, M13 9AN",
        "area": "Longsight",
        "phone": "01612733427",
        "dob": "14-Apr-1949",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230660,
        "name": "Christopher V Nugent",
        "address": "18 Grasscroft Close, Manchester, Lancashire, M14 7HQ",
        "area": "Chorlton",
        "phone": "0161 226 2982",
        "dob": "14-Feb-1941",
        "type": "MCC SPOT",
        "tags": "DNAR in place| Nitrofurantoin|",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 21,
        "name": "Lloyd Plummer",
        "address": "Flat 72 Clifford Court Chorlton Road, Manchester, Lancashire, M15 4AT",
        "area": "Chorlton",
        "phone": "07858880884, 01612260080",
        "dob": "13-Feb-1966",
        "type": "IB Budget",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230701,
        "name": "Sylvia  Reid",
        "address": "30 Mornington Crescent , Manchester, Greater Manchester, M14 6DE",
        "area": "Didsbury",
        "phone": "0161 286 0275",
        "dob": "27-Apr-1930",
        "type": "Private",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 76,
        "name": "James Scott",
        "address": "Flat 35 Egerton Court, Edge Lane, Manchester, M21 9HF",
        "area": "Chorlton",
        "phone": "0161 881 3148, 07920881349",
        "dob": "05-Jul-1953",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 106,
        "name": "Bibi Sharifan - St Werburghs Road",
        "address": "60 St Werburghs Road, Manchester, M21 0TJ",
        "area": "Chorlton",
        "phone": "0161 881 1140, Son-Ashraf -07886718582",
        "dob": "08-Nov-1936",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230501,
        "name": "Raymond Shaw",
        "address": "5 Brandwood Avenue, Chorlton, M21 7PJ, Manchester, M21 7PJ",
        "area": "Chorlton",
        "phone": "0161 445 2758, 07787305161 - Barry",
        "dob": "23-Mar-1952",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230552,
        "name": "Ethel Siddall",
        "address": "Flat 14 Arden Court, 1 Oakhouse Drive, Chorlton, Manchester, M21 8EW",
        "area": "Chorlton",
        "phone": "07709533294, 07709533294 - Lorraine",
        "dob": "24-Sep-1926",
        "type": "MCC SPOT",
        "tags": "DNAR in place| Dipyridamole| Dabigatran| Clopidogrel| Apixaban| Warfarin| Rivaroxaban| Penicillin|",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230632,
        "name": "Mohammed  Siddique",
        "address": "46 Clitheroe Road, Manchester, M13 0QN",
        "area": "Longsight",
        "phone": "07779887746",
        "dob": "01-Apr-1931",
        "type": "Private",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230508,
        "name": "Javed Syed",
        "address": "164 Seymour Grove, Old Trafford, M16 9GR, Manchester, M16 9GR",
        "area": "Chorlton",
        "phone": "07423112244 - Kashan, 07459243225 - Hina",
        "dob": "27-Mar-1953",
        "type": "Private",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230705,
        "name": "Simon Taun",
        "address": "7 Avro Close  Manchester , Manchester, M14 7FF",
        "area": "Chorlton",
        "phone": "0161 526 2105, 07737588187",
        "dob": "14-Mar-1964",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230280,
        "name": "Joshua Patrick Taylor",
        "address": "237 Darley Avenue, M21 7HR, Manchester, M21 7HR",
        "area": "Chorlton",
        "phone": "07875699723",
        "dob": "02-Sep-1990",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230392,
        "name": "Mildred Thompson",
        "address": "51 Pembroke Close,, Manchester, Lancashire, M13 9DY",
        "area": "Longsight",
        "phone": "07730021723 (Pam), 0161 274 3280",
        "dob": "22-Jan-1928",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230702,
        "name": "Francis Toland",
        "address": "Flat 47, Parkfield Court 38 - 40 Barlow Moor Road , Manchester, Greater Manchester, M20 2GE",
        "area": "Didsbury",
        "phone": "0161 445 4763, 07505913592",
        "dob": "09-Sep-1965",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230177,
        "name": "Peter Whalley",
        "address": "61 Hardy Lane, M21 7LG, Manchester, M21 7LG",
        "area": "Chorlton",
        "phone": "0161 861 0510",
        "dob": "28-Apr-1938",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230152,
        "name": "Hilda Wilkinson",
        "address": "87 Mersey Bank Lane, M21 7NT, Manchester, M21 7NT",
        "area": "Chorlton",
        "phone": "0161 434 1016",
        "dob": "06-May-1944",
        "type": "MCC SPOT",
        "tags": "DNAR in place",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230545,
        "name": "Julie Wilkinson",
        "address": "31 Sunny Brow Road, Manchester, M18 7AZ",
        "area": "Longsight",
        "phone": "07774502104, 07599041546 - Adrian",
        "dob": "05-Sep-1961",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230261,
        "name": "Joko Patrick Hendri Wilson",
        "address": "14 Whiteholme Avenue, M21 7PH, Manchester, M21 7PH",
        "area": "Chorlton",
        "phone": "Tracy - sister - 07931607953",
        "dob": "21-Oct-1936",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230436,
        "name": "Susan  Wilson",
        "address": "415 Greenwood Road , Manchester, County, M22 9RA",
        "area": "Wythenshawe",
        "phone": "07926299207, 07910940429- Son",
        "dob": "14-Aug-1959",
        "type": "MCC SPOT",
        "tags": "Penicillin",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": 230542,
        "name": "John Keith Winter",
        "address": "202 Portway, Woodhouse Park, Manchester, M22 1QW",
        "area": "Wythenshawe",
        "phone": "0161 283 6006, Janet winter - 07983991414",
        "dob": "07-Jan-1947",
        "type": "MCC SPOT",
        "tags": "",
        "status": "Active",
        "schedule": "Y",
        "details": "",
        "councilId": ""
      },
      {
        "_id": "",
        "name": "",
        "address": "",
        "area": "",
        "phone": "",
        "dob": "",
        "type": "",
        "tags": "",
        "status": "",
        "schedule": "",
        "details": "",
        "councilId": ""
      }
    ]

    // Simulate API call
    setTimeout(() => {
      setUserData(defaultClients);
      setMetaData({ total: defaultClients.length });
      setLoading(false);
    }, 500);
  }, []);

  return { userData, metaData, loading };
};
